Repository Ale6100/Proyecto-Polo-IT, pull requests merged in 2023-11, with the labels that each got.

#26 Añadi categorias y companias
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Categories.jsx
  frontend/src/components/Companies.jsx
  frontend/src/components/Footer.css
  frontend/src/components/Footer.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement

#27 Ft ale dev
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/models/companies.ts
  frontend/public/img/logo/2c5w.webp
  frontend/public/img/logo/activia.webp
  frontend/public/img/logo/altromondo.webp
  frontend/public/img/logo/anpro.webp
  frontend/public/img/logo/linksolution.webp
  frontend/public/img/logo/lucods.webp
  frontend/public/img/logo/remixCom.webp
  frontend/public/img/logo/sankalpatalent.webp
Labels: enhancement

#29 Ft ale dev
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  backend/src/routes/companies.routes.ts
  backend/src/types/company.d.ts
Labels: documentation, enhancement

#30 "Mejora del footer"
  frontend/public/img/social-media/icons8-facebook-32.png
  frontend/public/img/social-media/icons8-instagram-32.png
  frontend/public/img/social-media/icons8-linkedin-32.png
  frontend/public/img/social-media/icons8-twitter-32.png
  frontend/public/img/social-media/icons8-whatsapp-32.png
  frontend/public/img/social-media/icons8-youtube-32.png
  frontend/src/components/Footer.jsx
Labels: enhancement

#31 cambios en el diseño del footer, adaptacion para movile y tablet
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
Labels: documentation, enhancement

#32 Agregando vista Companies
  frontend/src/components/Categories.jsx
  frontend/src/components/Companies.jsx
  frontend/src/components/CompaniesList.jsx
  frontend/src/components/Footer.jsx
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement

#33 Ft ale dev
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  frontend/public/img/logo/c&s.webp
  frontend/public/img/logo/codes.webp
  frontend/public/img/logo/ctl.webp
  frontend/public/img/logo/disytel.webp
  frontend/public/img/logo/enfoke.png
  frontend/public/img/logo/epidata.webp
  frontend/public/img/logo/fcp.webp
  frontend/public/img/logo/gestionIt.webp
  frontend/public/img/logo/globemind.webp
Labels: enhancement

#34 Ft ese dev
  frontend/src/App.jsx
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/cardcompany.css
Labels: enhancement

#35 NavBar: Deslizamiento creado en el responsive | Active del NavLink terminado | Código simplificado
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
Labels: enhancement

#36 Agregado de empresas y paginación en Home
  frontend/.eslintrc.cjs
  frontend/src/App.jsx
  frontend/src/components/Categories.jsx
  frontend/src/components/Companies.jsx
  frontend/src/components/CompaniesList.jsx
  frontend/src/components/Company.css
  frontend/src/components/Company.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Home.jsx
Labels: enhancement

#37 cambios en los estilos de la seccion detalle,implementacion de react-…
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/cardcompany.css
  frontend/src/index.css
Labels: enhancement

#39 Ft ese dev
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/cardcompany.css
  frontend/src/index.css
Labels: enhancement

#40 Develop
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  backend/src/daos/models/companies.ts
  backend/src/routes/companies.routes.ts
  backend/src/types/company.d.ts
  frontend/.eslintrc.cjs
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/logo/2c5w.webp
  frontend/public/img/logo/activia.webp
  frontend/public/img/logo/altromondo.webp
  frontend/public/img/logo/anpro.webp
  frontend/public/img/logo/c&s.webp
  frontend/public/img/logo/codes.webp
  frontend/public/img/logo/ctl.webp
  frontend/public/img/logo/disytel.webp
  frontend/public/img/logo/enfoke.png
  frontend/public/img/logo/epidata.webp
  frontend/public/img/logo/fcp.webp
  frontend/public/img/logo/gestionIt.webp
  frontend/public/img/logo/globemind.webp
  frontend/public/img/logo/linksolution.webp
  frontend/public/img/logo/lucods.webp
  frontend/public/img/logo/remixCom.webp
  frontend/public/img/logo/sankalpatalent.webp
  frontend/public/img/social-media/icons8-facebook-32.png
  frontend/public/img/social-media/icons8-instagram-32.png
  frontend/public/img/social-media/icons8-linkedin-32.png
  frontend/public/img/social-media/icons8-twitter-32.png
  frontend/public/img/social-media/icons8-whatsapp-32.png
  frontend/public/img/social-media/icons8-youtube-32.png
  frontend/src/App.jsx
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Company.css
  frontend/src/components/Company.jsx
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/cardcompany.css
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/index.css
  frontend/src/main.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Home.jsx
Labels: documentation, enhancement, dependencies

#41 Formulario de contacto creado
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/disabledButton.js
  frontend/src/components/Navbar.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
Labels: enhancement

#42 Ft ale dev
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  backend/src/routes/companies.routes.ts
  frontend/index.html
  frontend/public/img/videoNoDisponible.webp
  frontend/src/App.jsx
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Loader.jsx
  frontend/src/components/cardcompany.css
  frontend/src/components/loader.css
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement

#43 Develop
  backend/README.md
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  backend/src/routes/companies.routes.ts
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/videoNoDisponible.webp
  frontend/src/App.jsx
  frontend/src/assets/disabledButton.js
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Loader.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/components/cardcompany.css
  frontend/src/components/loader.css
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Home.jsx
Labels: enhancement

#45 Ft ale dev
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/footer.styles.js
Labels: enhancement

#46 agregado de la seccion nosotros y el inicio, con sus archivos css
  frontend/src/App.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/about.css
  frontend/src/pages/inicio.css
Labels: enhancement

#47 agregado de diseño y contenido a la seccion inicio, con adaptacion fu…
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/Button.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/button.css
  frontend/src/index.css
  frontend/src/pages/About.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/inicio.css
Labels: enhancement

#48 Enrutamiento creado en /company/:page
  frontend/src/App.jsx
  frontend/src/components/Filter.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/pages/PageCompany.jsx
  frontend/src/pages/pageCompany.css
Labels: enhancement

#49 Responsive en la página /company
  frontend/public/img/configuration.svg
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/containers/CompaniesContainer.css
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
  frontend/src/pages/pageCompany.css
Labels: enhancement

#50 Icono agregado | Cambio dinámico de títulos | Loader centrado
  frontend/index.html
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Error404.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
Labels: enhancement

#51 Configurado envío individual de mails a las empresas
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Company.css
  frontend/src/components/cardcompany.css
  frontend/src/pages/Contact.jsx
Labels: enhancement

#52 Responsive mejorado en el detalle de las empresas | Icono de whatsapp…
  frontend/src/components/CardCompany.jsx
  frontend/src/components/cardcompany.css
Labels: enhancement

#53 Ft ese dev
  frontend/src/components/button.css
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/Services.jsx
  frontend/src/pages/inicio.css
  frontend/src/pages/services.css
Labels: enhancement

#54 Retoques menores
  frontend/README.md
  frontend/index.html
  frontend/src/components/Button.jsx
  frontend/src/components/CardCompany.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/inicio.css
Labels: enhancement

#55 Ft ese dev
  frontend/src/components/button.css
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Error404.css
  frontend/src/pages/Error404.jsx
  frontend/src/pages/Services.jsx
  frontend/src/pages/about.css
  frontend/src/pages/services.css
Labels: enhancement

#56 Develop
  frontend/README.md
  frontend/index.html
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/configuration.svg
  frontend/src/App.jsx
  frontend/src/components/Button.jsx
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Company.css
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/Navbar.css
  frontend/src/components/Navbar.jsx
  frontend/src/components/button.css
  frontend/src/components/cardcompany.css
  frontend/src/components/footer.styles.js
  frontend/src/containers/CompaniesContainer.css
  frontend/src/containers/CompaniesContainer.jsx
  frontend/src/index.css
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Error404.css
  frontend/src/pages/Error404.jsx
  frontend/src/pages/Home.css
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
  frontend/src/pages/about.css
  frontend/src/pages/inicio.css
  frontend/src/pages/pageCompany.css
Labels: enhancement

#57 Ft ale dev
  backend/README.md
  backend/src/app.ts
  backend/src/config/config.ts
  backend/src/controllers/companies.controllers.ts
  backend/src/routes/companies.routes.ts
  backend/src/services/mailingService.ts
  frontend/public/vite.svg
  frontend/src/assets/react.svg
  frontend/src/components/CardCompany.jsx
  frontend/src/components/button.css
  frontend/src/components/cardcompany.css
  frontend/src/index.css
  frontend/src/pages/Contact.css
  frontend/src/pages/PageCompany.jsx
  frontend/src/pages/inicio.css
Labels: enhancement

#58 Mejora de estilos para la seccion filter
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
Labels: enhancement

#59 Ft ese dev
  frontend/public/img/paginapolo.png
  frontend/src/components/Footer.jsx
  frontend/src/components/footer.styles.js
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/inicio.css
Labels: enhancement

#60 Puliendo detalles antes de terminar
  backend/src/daos/Container.ts
  frontend/index.html
  frontend/public/img/logo/base16.webp
  frontend/public/img/logo/hipernet.webp
  frontend/public/img/logo/informaticaTotal.webp
  frontend/public/img/logo/itr.webp
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Company.css
  frontend/src/components/Company.jsx
  frontend/src/components/Filter.css
  frontend/src/components/cardcompany.css
  frontend/src/containers/CompaniesContainer.css
  frontend/src/pages/Contact.css
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/about.css
  frontend/src/pages/inicio.css
Labels: enhancement

#61 Develop
  backend/README.md
  backend/src/app.ts
  backend/src/config/config.ts
  backend/src/controllers/companies.controllers.ts
  backend/src/daos/Container.ts
  backend/src/routes/companies.routes.ts
  backend/src/services/mailingService.ts
  frontend/index.html
  frontend/public/img/logo/base16.webp
  frontend/public/img/logo/hipernet.webp
  frontend/public/img/logo/informaticaTotal.webp
  frontend/public/img/logo/itr.webp
  frontend/public/img/paginapolo.png
  frontend/public/vite.svg
  frontend/src/assets/react.svg
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Company.css
  frontend/src/components/Company.jsx
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/button.css
  frontend/src/components/cardcompany.css
  frontend/src/components/footer.styles.js
  frontend/src/containers/CompaniesContainer.css
  frontend/src/index.css
  frontend/src/pages/Contact.css
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
  frontend/src/pages/about.css
  frontend/src/pages/inicio.css
Labels: enhancement

#62 Sistema de filtro mejorado, ya no olvida los valores seleccionados
  frontend/public/img/logo/voolkia.webp
  frontend/src/App.jsx
  frontend/src/assets/estructuraFormLimpio.js
  frontend/src/components/Filter.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
Labels: enhancement

#63 Cambios generales antes de entregar
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/CardCompany.jsx
  frontend/src/pages/Contact.jsx
Labels: enhancement

#64 Develop
  README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/img/logo/voolkia.webp
  frontend/src/App.jsx
  frontend/src/assets/estructuraFormLimpio.js
  frontend/src/components/CardCompany.jsx
  frontend/src/components/Filter.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/PageCompany.jsx
Labels: enhancement

#65 correción de errores de ortografia y cambio de contenido en la seccio…
  frontend/src/components/Footer.jsx
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Inicio.jsx
Labels: enhancement

#66 Último commit antes de entregar
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/footer.styles.js
  frontend/src/pages/pageCompany.css
  frontend/src/utils/ScrollCheck.jsx
Labels: enhancement

#67 Finished project!
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Filter.css
  frontend/src/components/Filter.jsx
  frontend/src/components/Footer.jsx
  frontend/src/components/footer.styles.js
  frontend/src/pages/About.jsx
  frontend/src/pages/Contact.css
  frontend/src/pages/Contact.jsx
  frontend/src/pages/Inicio.jsx
  frontend/src/pages/pageCompany.css
  frontend/src/utils/ScrollCheck.jsx
Labels: enhancement

#68 Commit adicional para eliminar una clase olvidada (con el permiso del…
  frontend/src/App.css
  frontend/src/App.jsx
Labels: enhancement

#69 Develop
  frontend/src/App.css
  frontend/src/App.jsx
Labels: enhancement

#70 ultimos cambios
  frontend/src/components/Company.css
  frontend/src/pages/inicio.css
Labels: enhancement, dependencies

#71 Servicio de mail inhabilitado
  README.md
  frontend/src/components/CardCompany.jsx
  frontend/src/pages/Contact.jsx
Labels: enhancement
